@startuml
left to right direction

actor "Пользователь" as User

User --> (Создать диаграмму с помощью кода)
User --> (Удалить диаграмму)
User --> (Предпросмотр диаграммы)
User --> (Экспорт диаграммы)
User --> (Импорт диаграммы)
User --> (Автосохранение диаграммы)
User --> (Авторизироваться через SSO)
User --> (Получить помощь ИИ)

(Создать диаграмму на PlantUML/Mermaid/GraphViz) <|-- (Создать диаграмму с помощью кода)

(Экспорт в PNG/TXT) <|-- (Экспорт диаграммы)

(Автосохранение диаграммы) .> (Сохранить диаграмму в GitLab) : <<include>>

@enduml

